name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main   # This is the branch where you want the workflow to run
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v23.7.0'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Deploy to EC2 (Dev Server)
      run: |
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          cd /path/to/your/repository
          git pull origin main
          pm2 restart app.js
     env:
        EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

